name: GraphQL Inspector

on: [push]

jobs:
  test:
    name: Check Schema
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: kamilkisiela/graphql-inspector@master
        with:
          name: "Check schema product"
          schema: "master:schema.graphql"
          fail-on-breaking: false

      - uses: kamilkisiela/graphql-inspector@master
        with:
          name: "Check product one"
          schema: "master:schema/one.graphql"
          fail-on-breaking: false

      - uses: kamilkisiela/graphql-inspector@master
        with:
          name: "Check product two"
          schema: "master:schema/two.graphql"
          fail-on-breaking: false
